services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP:-1000}'
        container_name: ${DOCKER_CONTAINER_NAME}_app
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
        networks:
            - devituz
        environment:
            APP_ENV: local
            WWWUSER: '${WWWUSER:-1000}'
            XDEBUG_MODE: '${XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${XDEBUG_CONFIG:-client_host=host.docker.internal}'
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        depends_on:
            - pgsql
            - redis
        restart: unless-stopped

    nginx:
        image: nginx:alpine
        container_name: ${DOCKER_CONTAINER_NAME}_nginx

        ports:
            - '${APP_PORT:-8000}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        volumes:
            - .:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - devituz
        restart: unless-stopped

    queue:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP:-1000}'
        container_name: ${DOCKER_CONTAINER_NAME}_queue

        command: php artisan queue:work
        volumes:
            - .:/var/www/html
        networks:
            - devituz
        depends_on:
            - pgsql
            - redis
        restart: unless-stopped

    pgsql:
        image: postgres:17
        container_name: ${DOCKER_CONTAINER_NAME}_pgsql

        ports:
            - '${FORWARD_DB_PORT:-5432}:5432'
        environment:
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
        volumes:
            - pgsql-data:/var/lib/postgresql/data
        networks:
            - devituz
        restart: unless-stopped

    redis:
        image: redis:alpine
        container_name: ${DOCKER_CONTAINER_NAME}_redis
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - ./redis.conf:/usr/local/etc/redis/redis.conf
            - redis-data:/data
        command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
        networks:
            - devituz
        restart: unless-stopped


    migration:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP:-1000}'
        container_name: ${DOCKER_CONTAINER_NAME}_migration
        command: |
            bash -c "php artisan migrate --seed && php artisan storage:link"
        depends_on:
            - app
            - pgsql
            - redis
        networks:
            - devituz
        environment:
            APP_ENV: local
        volumes:
            - .:/var/www/html
        restart: unless-stopped


volumes:
    pgsql-data:
    redis-data:

networks:
    devituz:
        driver: bridge
